./os os_0_mlq_paging  > logs/os_0_mlq_paging.output
./os os_1_mlq_paging > logs/os_1_mlq_paging.output
./os os_1_mlq_paging_small_1K > logs/os_1_mlq_paging_small_1K.output
./os os_1_mlq_paging_small_4K > logs/os_1_mlq_paging_small_4K.output
./os os_1_singleCPU_mlq > logs/os_1_singleCPU_mlq.output
./os os_1_singleCPU_mlq_paging > logs/os_1_singleCPU_mlq_paging.output
./os sched_0 > logs/sched_0.output
./os sched_1 > logs/sched_1.output
./os sched > logs/sched.output
./os os_sc > logs/os_sc.output
./os os_syscall > logs/os_syscall.output
./os os_syscall_list > logs/os_syscall_list.output
# mv logs/*.output logs
